### ISSUE TITLE
Using "CTRL+C + ..." shortcut breaks the copy shortcut

### ISSUE THREAD

**Issue by MLefebvreICO** [ergenekonyigit/vscode-wrap-console-log-lite#1]
Hi there,

Was trying your extension and it seemed nice until I was trying to copy/paste something in VSCode.
Since your extension uses `CTRL+C ...` shortcuts, it will simply break the copy shortcut and make it unusable.

Please check to change your default shortcuts.

**Comment by ergenekonyigit** [comment]
thanks report that. i will change shortcut to ```ctrl+shift+c ...```. this might fix that issue.

**Comment by ergenekonyigit** [comment]
fixed
